export const userRoleMap = {
  0: "Refrigerator",
  1: "Washer",
  2: "Dryer/Range",
  3: "Sales",
  4: "Office",
};

export const machineMap = {
  0: "Refrigerator",
  1: "Washer",
  2: "Dryer",
  3: "Range",
  4: "Stackable",
  5: "Microwave",
  6: "Water Heater",
};

export const brands = {
  Admiral: "Admiral",
  Amana: "Amana",
  "Arctic King": "Arctic King",
  "Ascoli America": "Ascoli America",
  Avanti: "Avanti",
  Bosch: "Bosch",
  Cafe: "Cafe",
  "Comfort Aire": "Comfort Aire",
  Conservator: "Conservator",
  Crosley: "Crosley",
  Cuisinart: "Cuisinart",
  Danby: "Danby",
  Electrolux: "Electrolux",
  Estate: "Estate",
  "Fisher & Paykel": "Fisher & Paykel",
  Fridgidaire: "Fridgidaire",
  "Fridgidaire Gallery": "Fridgidaire Gallery",
  "Fridgidaire Professional": "Fridgidaire Professional",
  GE: "GE",
  "GE Profile": "GE Profile",
  Haier: "Haier",
  Hisense: "Hisense",
  Hotpoint: "Hotpoint",
  Inglis: "Inglis",
  "Jenn-Air": "Jenn-Air",
  Kenmore: "Kenmore",
  Kitchenaid: "Kitchenaid",
  LG: "LG",
  "LG Signature": "LG Signature",
  "Magic Chef": "Magic Chef",
  Maytag: "Maytag",
  Midea: "Midea",
  Richmond: "Richmond",
  Roper: "Roper",
  Samsung: "Samsung",
  "Speed Queen": "Speed Queen",
  Tappan: "Tappan",
  Whirlpool: "Whirlpool",
  "White-Westinghouse": "White-Westinghouse",
};

export const colors = {
  Black: "Black",
  "Black Stainless": "Black Stainless",
  Blue: "Blue",
  Bronze: "Bronze",
  Brown: "Brown",
  Champagne: "Champagne",
  Cream: "Cream",
  Gold: "Gold",
  Green: "Green",
  Grey: "Grey",
  Orange: "Orange",
  Other: "Other",
  "Panel Ready": "Panel Ready",
  Purple: "Purple",
  Red: "Red",
  Silver: "Silver",
  Stainless: "Stainless",
  Teal: "Teal",
  White: "White",
  "White Stainless": "White Stainless",
  Wood: "Wood",
  Yellow: "Yellow",
};

export const machineStyles = {
  fridge: {
    "Top & Bottom": "Top & Bottom",
    "Side by Side": "Side by Side",
    "French Door": "French Door",
    "Bottom Mount": "Bottom Mount",
    Upright: "Upright",
    Chest: "Chest",
  },
  washer: {
    "Top Load": "Top Load",
    "Front Load": "Front Load",
    "All in One": "All in One",
  },
  dryer: {
    "Top Load Gas": "Top Load Gas",
    "Front Load Gas": "Front Load Gas",
    "Top Load Electric": "Top Load Electric",
    "Front Load Electric": "Front Load Electric",
    "All in One": "All in One",
  },
  range: {
    Gas: "Gas",
    Coil: "Coil",
    "Glass Top": "Glass Top",
  },
};

export const vendors = {
  Pasadena: "Pasadena",
  "Baton Rouge": "Baton Rouge",
  Alexandria: "Alexandria",
  "Stines LC": "Stines LC",
  "Stines Jenings": "Stines Jennings",
  Scrappers: "Scrappers",
  Unknown: "Unknown",
};

export const conditions = {
  NEW: "NEW",
  USED: "USED",
  "Scratch and Dent": "Scratch and Dent",
};
