"""added inventory boolean and archive status to enum

Revision ID: 00be436e8c43
Revises: 
Create Date: 2025-09-26 15:27:26.623815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00be436e8c43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('need_to_inventory', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('need_to_inventory')

    # ### end Alembic commands ###
