"""updated machine table to have cols for cleaners, going to try and focus on sending a machine all the way through matts. added cleaned_on and cleaned_by cols

Revision ID: 00f5f8610c77
Revises: 637fa895b6e3
Create Date: 2025-06-17 23:13:17.729449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00f5f8610c77'
down_revision = '637fa895b6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repaired_on', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('repaired_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cleaned_on', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('cleaned_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_clean', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(batch_op.f('machine_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['cleaned_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'user', ['repaired_by'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('finished_by')
        batch_op.drop_column('finished_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finished_on', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('finished_by', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('machine_ibfk_1'), 'user', ['finished_by'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('is_clean')
        batch_op.drop_column('cleaned_by')
        batch_op.drop_column('cleaned_on')
        batch_op.drop_column('repaired_by')
        batch_op.drop_column('repaired_on')

    # ### end Alembic commands ###
