"""added roles to users, with role Enum

Revision ID: 060d6042fb2f
Revises: 30193e982693
Create Date: 2025-06-17 13:30:37.985321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060d6042fb2f'
down_revision = '30193e982693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Enum('Technician', 'Cleaner', 'Sales', 'Office', 'Driver', 'Service', name='positions'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
