"""added trashed_by columns as well

Revision ID: 0657e2805868
Revises: f5c6eb2469c5
Create Date: 2025-10-15 09:54:10.844048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0657e2805868'
down_revision = 'f5c6eb2469c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trashed_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['trashed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('trashed_by')

    # ### end Alembic commands ###
