"""Added new columns to Inventory and Archives

Revision ID: 0b434a2dc142
Revises: 
Create Date: 2025-02-07 23:01:32.279352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b434a2dc142'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_on', sa.Date(), nullable=True))

    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.String(length=50), server_default='USED', nullable=True))
        batch_op.add_column(sa.Column('created_on', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('created_on')
        batch_op.drop_column('condition')

    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.drop_column('added_on')

    # ### end Alembic commands ###
