"""added is_complete to Task model

Revision ID: 30193e982693
Revises: 
Create Date: 2025-06-16 23:44:56.662780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30193e982693'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_complete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('is_complete')

    # ### end Alembic commands ###
