"""added date column to Machine table, finished_on

Revision ID: 637fa895b6e3
Revises: 060d6042fb2f
Create Date: 2025-06-17 22:28:41.284277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637fa895b6e3'
down_revision = '060d6042fb2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finished_on', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('finished_on')

    # ### end Alembic commands ###
