"""Deleted archive table

Revision ID: 79f958e5c5ab
Revises: 
Create Date: 2025-05-09 23:40:51.971953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79f958e5c5ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.drop_constraint('notes_ibfk_3', 'notes', type_='foreignkey')
    op.drop_column('notes', 'archive_id')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archive')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('archive',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brand', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('model', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('serial', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('color', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('style', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('condition', mysql.VARCHAR(length=50), server_default=sa.text("'USED'"), nullable=True),
    sa.Column('created_on', sa.DATE(), nullable=True),
    sa.Column('in_progress', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('machine_type', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    
    
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archive_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('notes_ibfk_3', 'archive', ['archive_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
