"""empty message

Revision ID: 7c4a777c1cb4
Revises: bec66e047971
Create Date: 2025-03-09 21:03:30.389451

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c4a777c1cb4'
down_revision = 'bec66e047971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machine_dryer')
    op.drop_table('machine')
    op.drop_table('machine_fridge')
    op.drop_table('machine_washer')
    op.drop_table('machine_range')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_range',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('make', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('model', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('serial', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('color', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('style', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('heat_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('condition', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('created_on', sa.DATE(), nullable=True),
    sa.Column('in_progress', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('machine_washer',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('make', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('model', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('serial', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('color', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('style', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('condition', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('created_on', sa.DATE(), nullable=True),
    sa.Column('in_progress', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('machine_fridge',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('make', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('model', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('serial', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('color', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('style', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('condition', mysql.VARCHAR(length=50), server_default=sa.text("'USED'"), nullable=True),
    sa.Column('created_on', sa.DATE(), nullable=True),
    sa.Column('in_progress', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('machine',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('make', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('model', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('serial', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('color', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('style', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('condition', mysql.VARCHAR(length=50), server_default=sa.text("'USED'"), nullable=True),
    sa.Column('created_on', sa.DATE(), nullable=True),
    sa.Column('in_progress', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('machine_dryer',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('make', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('model', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('serial', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('color', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('style', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('heat_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('condition', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('created_on', sa.DATE(), nullable=True),
    sa.Column('in_progress', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
