"""added in_inventory col to machine ORM

Revision ID: 902412828bd2
Revises: 92efceb1aa05
Create Date: 2025-05-08 14:07:10.330042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902412828bd2'
down_revision = '92efceb1aa05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_inventory', sa.Boolean(), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('in_inventory')

    # ### end Alembic commands ###
