"""added validation to some Machine fields

Revision ID: 91e4e2ef2506
Revises: 
Create Date: 2025-05-15 13:53:11.349075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91e4e2ef2506'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.alter_column('brand',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('model',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('serial',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
        batch_op.create_unique_constraint(None, ['serial'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('serial',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('model',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('brand',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###
