"""Baseline after clean up and removed heat_type col

Revision ID: 92efceb1aa05
Revises: a1cfc106faed
Create Date: 2025-05-08 11:58:52.193926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92efceb1aa05'
down_revision = 'a1cfc106faed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.drop_column('heat_type')
        batch_op.drop_column('added_on')

    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('heat_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heat_type', mysql.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_on', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('heat_type', mysql.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
