"""dropped heat_type column from machine

Revision ID: a1cfc106faed
Revises: 
Create Date: 2025-05-08 11:57:28.003235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1cfc106faed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.drop_column('added_on')
        batch_op.drop_column('heat_type')

    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_column('heat_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heat_type', mysql.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heat_type', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('added_on', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
