"""update to Machine model with status

Revision ID: ace450de4574
Revises: 00f5f8610c77
Create Date: 2025-07-30 00:12:21.401252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ace450de4574'
down_revision = '00f5f8610c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('queued', 'cleaned', 'export', 'deleted', name='status_enum'), nullable=True))
        batch_op.drop_column('is_exported')
        batch_op.drop_column('is_clean')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_clean', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_exported', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
