"""empty message

Revision ID: bec66e047971
Revises: 0b434a2dc142
Create Date: 2025-02-08 00:47:27.078887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec66e047971'
down_revision = '0b434a2dc142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.String(length=50), server_default='USED', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.drop_column('condition')

    # ### end Alembic commands ###
