"""added completed_by column to Machine and used chatGPT to setup method for getting machines a user has completed

Revision ID: f5c6eb2469c5
Revises: 00be436e8c43
Create Date: 2025-10-15 09:06:48.635638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5c6eb2469c5'
down_revision = '00be436e8c43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['completed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('completed_by')

    # ### end Alembic commands ###
